#!/usr/bin/env python3
"""
PeaZipMenu — ClickMesh-generated context menu extension for Nemo (Cinnamon).
Auto-generated by ClickMesh. Edit the source JSON and re-generate instead of
modifying this file directly.
"""

import os
import shlex
import subprocess
import shutil
import threading
from urllib.parse import unquote

import gi
from gi.repository import Nemo, GObject

# ---------------------------------------------------------------------------
#  Helpers
# ---------------------------------------------------------------------------

def _localize(val):
    if isinstance(val, str): return val
    lang = os.environ.get('LANG', 'en').split('.')[0].split('_')[0]
    return val.get(lang, val.get('en', next(iter(val.values())) if val else ''))

def _path_from_item(file_item):
    """Extract a local filesystem path from a Nemo FileInfo object."""
    uri = file_item.get_uri()
    if uri.startswith("file://"):
        return unquote(uri[7:])
    return unquote(uri)

def _confirm(message: str) -> bool:
    if shutil.which('zenity'):
        res = subprocess.run(['zenity', '--question', '--text', message], capture_output=True)
        return res.returncode == 0
    if shutil.which('kdialog'):
        res = subprocess.run(['kdialog', '--yesno', message], capture_output=True)
        return res.returncode == 0
    return True

def _show_error(message: str):
    if shutil.which('zenity'):
        subprocess.run(['zenity', '--error', '--text', message])
    elif shutil.which('kdialog'):
        subprocess.run(['kdialog', '--error', message])
    elif shutil.which('notify-send'):
        subprocess.run(['notify-send', '-i', 'dialog-error', 'ClickMesh Error', message])

def _run_in_terminal(cmd: str, shell: bool = False):
    terms = ['x-terminal-emulator', 'gnome-terminal', 'konsole', 'xfce4-terminal', 'xterm']
    term = next((t for t in terms if shutil.which(t)), None)
    
    if not term:
        if shell:
            subprocess.Popen(cmd, shell=True, start_new_session=True)
        else:
            subprocess.Popen(shlex.split(cmd), start_new_session=True)
        return

    if shell:
        script = f"{cmd}; echo; read -p 'Press Enter to close...'"
        if term in ['gnome-terminal', '/usr/bin/gnome-terminal']:
            subprocess.Popen([term, '--', 'bash', '-c', script], start_new_session=True)
        else:
            subprocess.Popen([term, '-e', 'bash', '-c', script], start_new_session=True)
    else:
        cmd_args = shlex.split(cmd)
        script = 'mcmd="$1"; shift; "$mcmd" "$@"; echo; read -p "Press Enter to close..."'
        if term in ['gnome-terminal', '/usr/bin/gnome-terminal']:
            subprocess.Popen([term, '--', 'bash', '-c', script, '_'] + cmd_args, start_new_session=True)
        else:
            subprocess.Popen([term, '-e', 'bash', '-c', script, '_'] + cmd_args, start_new_session=True)

def _execute_cmds(cmds: list, show_output: bool, notify: bool, name: str, shell: bool = False):
    def worker():
        for cmd in cmds:
            if show_output:
                _run_in_terminal(cmd, shell)
            else:
                if shell:
                    subprocess.Popen(cmd, shell=True, start_new_session=True)
                else:
                    subprocess.Popen(shlex.split(cmd), start_new_session=True)
        if notify:
            subprocess.Popen(["notify-send", "-i", "dialog-information", "ClickMesh", f"Action '{name}' completed."], start_new_session=True)
    threading.Thread(target=worker, daemon=True).start()

# ---------------------------------------------------------------------------
#  Action callbacks
# ---------------------------------------------------------------------------

def _on_action_0(menu_item, files):
    """Callback: Open Archive"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2browse %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Open Archive', shell=False)


def _on_action_1(menu_item, files):
    """Callback: Extract Here"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2here %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract Here', shell=False)


def _on_action_2(menu_item, files):
    """Callback: Extract to Folder"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2newfolder %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract to Folder', shell=False)


def _on_action_3(menu_item, files):
    """Callback: Extract to... (Choose Folder)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'fm=$(xdg-mime query default inode/directory 2>/dev/null); case "$fm" in *dolphin*|*kde*|*qt*|*konqueror*) pick=kdialog;; *) pick=zenity;; esac; command -v "$pick" >/dev/null 2>&1 || { pick=zenity; command -v zenity >/dev/null 2>&1 || pick=kdialog; }; if [ "$pick" = kdialog ]; then out=$(kdialog --getexistingdirectory %dir/); else out=$(zenity --file-selection --directory --title="PeaZip" --filename=%dir/); fi; [ -n "$out" ] && peazip -ext2here -o "$out" %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract to... (Choose Folder)', shell=True)


def _on_action_4(menu_item, files):
    """Callback: Extract with Options..."""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2main %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract with Options...', shell=False)


def _on_action_5(menu_item, files):
    """Callback: Test Archive"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2test %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Test Archive', shell=False)


def _on_action_6(menu_item, files):
    """Callback: Add to Archive..."""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2archive %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to Archive...', shell=False)


def _on_action_7(menu_item, files):
    """Callback: Add to ZIP"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2zip %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to ZIP', shell=False)


def _on_action_8(menu_item, files):
    """Callback: Add to 7Z"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add27z %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to 7Z', shell=False)


def _on_action_9(menu_item, files):
    """Callback: Add to TAR.GZ"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2gzip %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to TAR.GZ', shell=False)


def _on_action_10(menu_item, files):
    """Callback: Add to TAR.XZ"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2xz %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to TAR.XZ', shell=False)


def _on_action_11(menu_item, files):
    """Callback: Add to TAR.ZST"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2zstd %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to TAR.ZST', shell=False)


def _on_action_12(menu_item, files):
    """Callback: Create Encrypted Archive (PEA)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2crypt %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Create Encrypted Archive (PEA)', shell=False)


def _on_action_13(menu_item, files):
    """Callback: Create SFX Archive (7Z)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2sfx7z %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Create SFX Archive (7Z)', shell=False)


def _on_action_14(menu_item, files):
    """Callback: Split into Volumes"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2split %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Split into Volumes', shell=False)


# ---------------------------------------------------------------------------
#  Menu Provider
# ---------------------------------------------------------------------------

class PeazipmenuExtension(GObject.GObject, Nemo.MenuProvider):
    """Injects a '{{MENU_TITLE}}' submenu into the Nemo right-click menu."""

    def get_file_items(self, window, files):
        if not files:
            return []

        # --- ClickMesh Filtering (Per-Item Basis Setup) ---
        allow_dirs = True
        paths = [_path_from_item(f) for f in files]
        has_dir = any(os.path.isdir(p) for p in paths)
        has_file = any(not os.path.isdir(p) for p in paths)

        if has_dir and not allow_dirs:
            return []
        # --------------------------------------------------

        top_item = Nemo.MenuItem(
            name="PeaZipMenu::TopMenu",
            label=_localize({'en': 'PeaZip', 'ar': 'بيزيب'}),
            tip=_localize({'en': 'PeaZip', 'ar': 'بيزيب'}),
            icon="peazip",
        )
        submenu = Nemo.Menu()
        top_item.set_submenu(submenu)

        items_added = 0
        # --- Menu Tree Setup ---
        menus = {'': submenu}
        item_0_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso', '.cab', '.arj')
        item_0_allow_all = False
        show_item_0 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_0 = True
            elif has_file:
                if item_0_allow_all:
                    show_item_0 = True
                else:
                    show_item_0 = any(any(p.lower().endswith(ext) for ext in item_0_exts) for p in paths if not os.path.isdir(p))

        if show_item_0:
            item_0 = Nemo.MenuItem(
                name="PeaZipMenu::Action0",
                label=_localize({'en': 'Open Archive', 'ar': 'فتح الأرشيف'}),
                tip=_localize({'en': 'Open Archive', 'ar': 'فتح الأرشيف'}),
                icon="peazip",
            )
            item_0.connect("activate", _on_action_0, files)
            menus[''].append_item(item_0)
            items_added += 1
        item_1_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso', '.cab', '.arj')
        item_1_allow_all = False
        show_item_1 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_1 = True
            elif has_file:
                if item_1_allow_all:
                    show_item_1 = True
                else:
                    show_item_1 = any(any(p.lower().endswith(ext) for ext in item_1_exts) for p in paths if not os.path.isdir(p))

        if show_item_1:
            if 'Extract' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_1 = Nemo.MenuItem(
                name="PeaZipMenu::Action1",
                label=_localize({'en': 'Extract Here', 'ar': 'استخراج هنا'}),
                tip=_localize({'en': 'Extract Here', 'ar': 'استخراج هنا'}),
                icon="archive-extract",
            )
            item_1.connect("activate", _on_action_1, files)
            menus['Extract'].append_item(item_1)
            items_added += 1
        item_2_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso', '.cab', '.arj')
        item_2_allow_all = False
        show_item_2 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_2 = True
            elif has_file:
                if item_2_allow_all:
                    show_item_2 = True
                else:
                    show_item_2 = any(any(p.lower().endswith(ext) for ext in item_2_exts) for p in paths if not os.path.isdir(p))

        if show_item_2:
            if 'Extract' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_2 = Nemo.MenuItem(
                name="PeaZipMenu::Action2",
                label=_localize({'en': 'Extract to Folder', 'ar': 'استخراج إلى مجلد'}),
                tip=_localize({'en': 'Extract to Folder', 'ar': 'استخراج إلى مجلد'}),
                icon="folder-new",
            )
            item_2.connect("activate", _on_action_2, files)
            menus['Extract'].append_item(item_2)
            items_added += 1
        item_3_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso', '.cab', '.arj')
        item_3_allow_all = False
        show_item_3 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_3 = True
            elif has_file:
                if item_3_allow_all:
                    show_item_3 = True
                else:
                    show_item_3 = any(any(p.lower().endswith(ext) for ext in item_3_exts) for p in paths if not os.path.isdir(p))

        if show_item_3:
            if 'Extract' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_3 = Nemo.MenuItem(
                name="PeaZipMenu::Action3",
                label=_localize({'en': 'Extract to... (Choose Folder)', 'ar': 'استخراج إلى... (اختيار المجلد)'}),
                tip=_localize({'en': 'Extract to... (Choose Folder)', 'ar': 'استخراج إلى... (اختيار المجلد)'}),
                icon="folder-open",
            )
            item_3.connect("activate", _on_action_3, files)
            menus['Extract'].append_item(item_3)
            items_added += 1
        item_4_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso', '.cab', '.arj')
        item_4_allow_all = False
        show_item_4 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_4 = True
            elif has_file:
                if item_4_allow_all:
                    show_item_4 = True
                else:
                    show_item_4 = any(any(p.lower().endswith(ext) for ext in item_4_exts) for p in paths if not os.path.isdir(p))

        if show_item_4:
            if 'Extract' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_4 = Nemo.MenuItem(
                name="PeaZipMenu::Action4",
                label=_localize({'en': 'Extract with Options...', 'ar': 'استخراج بخيارات...'}),
                tip=_localize({'en': 'Extract with Options...', 'ar': 'استخراج بخيارات...'}),
                icon="preferences-system",
            )
            item_4.connect("activate", _on_action_4, files)
            menus['Extract'].append_item(item_4)
            items_added += 1
        item_5_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso', '.cab', '.arj')
        item_5_allow_all = False
        show_item_5 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_5 = True
            elif has_file:
                if item_5_allow_all:
                    show_item_5 = True
                else:
                    show_item_5 = any(any(p.lower().endswith(ext) for ext in item_5_exts) for p in paths if not os.path.isdir(p))

        if show_item_5:
            if 'Extract' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_5 = Nemo.MenuItem(
                name="PeaZipMenu::Action5",
                label=_localize({'en': 'Test Archive', 'ar': 'فحص الأرشيف'}),
                tip=_localize({'en': 'Test Archive', 'ar': 'فحص الأرشيف'}),
                icon="emblem-ok-symbolic",
            )
            item_5.connect("activate", _on_action_5, files)
            menus['Extract'].append_item(item_5)
            items_added += 1
        item_6_exts = ()
        item_6_allow_all = True
        show_item_6 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_6 = True
            elif has_file:
                if item_6_allow_all:
                    show_item_6 = True
                else:
                    show_item_6 = any(any(p.lower().endswith(ext) for ext in item_6_exts) for p in paths if not os.path.isdir(p))

        if show_item_6:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            item_6 = Nemo.MenuItem(
                name="PeaZipMenu::Action6",
                label=_localize({'en': 'Add to Archive...', 'ar': 'إضافة لأرشيف... (خيارات)'}),
                tip=_localize({'en': 'Add to Archive...', 'ar': 'إضافة لأرشيف... (خيارات)'}),
                icon="archive-insert",
            )
            item_6.connect("activate", _on_action_6, files)
            menus['Add to Archive'].append_item(item_6)
            items_added += 1
        item_7_exts = ()
        item_7_allow_all = True
        show_item_7 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_7 = True
            elif has_file:
                if item_7_allow_all:
                    show_item_7 = True
                else:
                    show_item_7 = any(any(p.lower().endswith(ext) for ext in item_7_exts) for p in paths if not os.path.isdir(p))

        if show_item_7:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            item_7 = Nemo.MenuItem(
                name="PeaZipMenu::Action7",
                label=_localize({'en': 'Add to ZIP', 'ar': 'إضافة إلى ZIP'}),
                tip=_localize({'en': 'Add to ZIP', 'ar': 'إضافة إلى ZIP'}),
                icon="package-x-generic",
            )
            item_7.connect("activate", _on_action_7, files)
            menus['Add to Archive'].append_item(item_7)
            items_added += 1
        item_8_exts = ()
        item_8_allow_all = True
        show_item_8 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_8 = True
            elif has_file:
                if item_8_allow_all:
                    show_item_8 = True
                else:
                    show_item_8 = any(any(p.lower().endswith(ext) for ext in item_8_exts) for p in paths if not os.path.isdir(p))

        if show_item_8:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            item_8 = Nemo.MenuItem(
                name="PeaZipMenu::Action8",
                label=_localize({'en': 'Add to 7Z', 'ar': 'إضافة إلى 7Z'}),
                tip=_localize({'en': 'Add to 7Z', 'ar': 'إضافة إلى 7Z'}),
                icon="package-x-generic",
            )
            item_8.connect("activate", _on_action_8, files)
            menus['Add to Archive'].append_item(item_8)
            items_added += 1
        item_9_exts = ()
        item_9_allow_all = True
        show_item_9 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_9 = True
            elif has_file:
                if item_9_allow_all:
                    show_item_9 = True
                else:
                    show_item_9 = any(any(p.lower().endswith(ext) for ext in item_9_exts) for p in paths if not os.path.isdir(p))

        if show_item_9:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Other Formats' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive/Other Formats', label=_localize({'en': 'Other Formats', 'ar': 'صيغ أخرى'}), tip=_localize({'en': 'Other Formats', 'ar': 'صيغ أخرى'}), icon='package-x-generic')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Other Formats'] = group_menu
            item_9 = Nemo.MenuItem(
                name="PeaZipMenu::Action9",
                label=_localize({'en': 'Add to TAR.GZ', 'ar': 'إضافة إلى TAR.GZ'}),
                tip=_localize({'en': 'Add to TAR.GZ', 'ar': 'إضافة إلى TAR.GZ'}),
                icon="package-x-generic",
            )
            item_9.connect("activate", _on_action_9, files)
            menus['Add to Archive/Other Formats'].append_item(item_9)
            items_added += 1
        item_10_exts = ()
        item_10_allow_all = True
        show_item_10 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_10 = True
            elif has_file:
                if item_10_allow_all:
                    show_item_10 = True
                else:
                    show_item_10 = any(any(p.lower().endswith(ext) for ext in item_10_exts) for p in paths if not os.path.isdir(p))

        if show_item_10:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Other Formats' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive/Other Formats', label=_localize({'en': 'Other Formats', 'ar': 'صيغ أخرى'}), tip=_localize({'en': 'Other Formats', 'ar': 'صيغ أخرى'}), icon='package-x-generic')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Other Formats'] = group_menu
            item_10 = Nemo.MenuItem(
                name="PeaZipMenu::Action10",
                label=_localize({'en': 'Add to TAR.XZ', 'ar': 'إضافة إلى TAR.XZ'}),
                tip=_localize({'en': 'Add to TAR.XZ', 'ar': 'إضافة إلى TAR.XZ'}),
                icon="package-x-generic",
            )
            item_10.connect("activate", _on_action_10, files)
            menus['Add to Archive/Other Formats'].append_item(item_10)
            items_added += 1
        item_11_exts = ()
        item_11_allow_all = True
        show_item_11 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_11 = True
            elif has_file:
                if item_11_allow_all:
                    show_item_11 = True
                else:
                    show_item_11 = any(any(p.lower().endswith(ext) for ext in item_11_exts) for p in paths if not os.path.isdir(p))

        if show_item_11:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Other Formats' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive/Other Formats', label=_localize({'en': 'Other Formats', 'ar': 'صيغ أخرى'}), tip=_localize({'en': 'Other Formats', 'ar': 'صيغ أخرى'}), icon='package-x-generic')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Other Formats'] = group_menu
            item_11 = Nemo.MenuItem(
                name="PeaZipMenu::Action11",
                label=_localize({'en': 'Add to TAR.ZST', 'ar': 'إضافة إلى TAR.ZST'}),
                tip=_localize({'en': 'Add to TAR.ZST', 'ar': 'إضافة إلى TAR.ZST'}),
                icon="package-x-generic",
            )
            item_11.connect("activate", _on_action_11, files)
            menus['Add to Archive/Other Formats'].append_item(item_11)
            items_added += 1
        item_12_exts = ()
        item_12_allow_all = True
        show_item_12 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_12 = True
            elif has_file:
                if item_12_allow_all:
                    show_item_12 = True
                else:
                    show_item_12 = any(any(p.lower().endswith(ext) for ext in item_12_exts) for p in paths if not os.path.isdir(p))

        if show_item_12:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Advanced & Security' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive/Advanced & Security', label=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), tip=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), icon='preferences-system-security')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Advanced & Security'] = group_menu
            item_12 = Nemo.MenuItem(
                name="PeaZipMenu::Action12",
                label=_localize({'en': 'Create Encrypted Archive (PEA)', 'ar': 'إنشاء أرشيف مشفر (PEA)'}),
                tip=_localize({'en': 'Create Encrypted Archive (PEA)', 'ar': 'إنشاء أرشيف مشفر (PEA)'}),
                icon="dialog-password",
            )
            item_12.connect("activate", _on_action_12, files)
            menus['Add to Archive/Advanced & Security'].append_item(item_12)
            items_added += 1
        item_13_exts = ()
        item_13_allow_all = True
        show_item_13 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_13 = True
            elif has_file:
                if item_13_allow_all:
                    show_item_13 = True
                else:
                    show_item_13 = any(any(p.lower().endswith(ext) for ext in item_13_exts) for p in paths if not os.path.isdir(p))

        if show_item_13:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Advanced & Security' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive/Advanced & Security', label=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), tip=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), icon='preferences-system-security')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Advanced & Security'] = group_menu
            item_13 = Nemo.MenuItem(
                name="PeaZipMenu::Action13",
                label=_localize({'en': 'Create SFX Archive (7Z)', 'ar': 'أرشيف ذاتي الاستخراج (SFX)'}),
                tip=_localize({'en': 'Create SFX Archive (7Z)', 'ar': 'أرشيف ذاتي الاستخراج (SFX)'}),
                icon="application-x-executable",
            )
            item_13.connect("activate", _on_action_13, files)
            menus['Add to Archive/Advanced & Security'].append_item(item_13)
            items_added += 1
        item_14_exts = ()
        item_14_allow_all = True
        show_item_14 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_14 = True
            elif has_file:
                if item_14_allow_all:
                    show_item_14 = True
                else:
                    show_item_14 = any(any(p.lower().endswith(ext) for ext in item_14_exts) for p in paths if not os.path.isdir(p))

        if show_item_14:
            if 'Add to Archive' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Advanced & Security' not in menus:
                group_item = Nemo.MenuItem(name='PeaZipMenu::Add to Archive/Advanced & Security', label=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), tip=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), icon='preferences-system-security')
                group_menu = Nemo.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Advanced & Security'] = group_menu
            item_14 = Nemo.MenuItem(
                name="PeaZipMenu::Action14",
                label=_localize({'en': 'Split into Volumes', 'ar': 'تقسيم الملف إلى أجزاء'}),
                tip=_localize({'en': 'Split into Volumes', 'ar': 'تقسيم الملف إلى أجزاء'}),
                icon="view-split-left-right",
            )
            item_14.connect("activate", _on_action_14, files)
            menus['Add to Archive/Advanced & Security'].append_item(item_14)
            items_added += 1
        if items_added == 0:
            return []

        return [top_item]
