#!/usr/bin/env python3
"""
PeaZipMenu — ClickMesh-generated context menu extension for Thunar (XFCE).
Auto-generated by ClickMesh. Edit the source JSON and re-generate instead of
modifying this file directly.
"""

import os
import shlex
import subprocess
import shutil
import threading
from urllib.parse import unquote

import gi
gi.require_version("Thunarx", "3.0")
from gi.repository import GObject, Thunarx

# ---------------------------------------------------------------------------
#  Helpers
# ---------------------------------------------------------------------------

def _localize(val):
    if isinstance(val, str): return val
    lang = os.environ.get('LANG', 'en').split('.')[0].split('_')[0]
    return val.get(lang, val.get('en', next(iter(val.values())) if val else ''))

def _path_from_item(file_item):
    """Extract a local filesystem path from a Thunarx FileInfo object."""
    uri = file_item.get_uri()
    if uri.startswith("file://"):
        return unquote(uri[7:])
    return unquote(uri)

def _confirm(message: str) -> bool:
    if shutil.which('zenity'):
        res = subprocess.run(['zenity', '--question', '--text', message], capture_output=True)
        return res.returncode == 0
    if shutil.which('kdialog'):
        res = subprocess.run(['kdialog', '--yesno', message], capture_output=True)
        return res.returncode == 0
    return True

def _show_error(message: str):
    if shutil.which('zenity'):
        subprocess.run(['zenity', '--error', '--text', message])
    elif shutil.which('kdialog'):
        subprocess.run(['kdialog', '--error', message])
    elif shutil.which('notify-send'):
        subprocess.run(['notify-send', '-i', 'dialog-error', 'ClickMesh Error', message])

def _run_in_terminal(cmd: str, shell: bool = False):
    terms = ['x-terminal-emulator', 'gnome-terminal', 'konsole', 'xfce4-terminal', 'xterm']
    term = next((t for t in terms if shutil.which(t)), None)
    
    if not term:
        if shell:
            subprocess.Popen(cmd, shell=True, start_new_session=True)
        else:
            subprocess.Popen(shlex.split(cmd), start_new_session=True)
        return

    if shell:
        script = f"{cmd}; echo; read -p 'Press Enter to close...'"
        if term in ['gnome-terminal', '/usr/bin/gnome-terminal']:
            subprocess.Popen([term, '--', 'bash', '-c', script], start_new_session=True)
        else:
            subprocess.Popen([term, '-e', 'bash', '-c', script], start_new_session=True)
    else:
        cmd_args = shlex.split(cmd)
        script = 'mcmd="$1"; shift; "$mcmd" "$@"; echo; read -p "Press Enter to close..."'
        if term in ['gnome-terminal', '/usr/bin/gnome-terminal']:
            subprocess.Popen([term, '--', 'bash', '-c', script, '_'] + cmd_args, start_new_session=True)
        else:
            subprocess.Popen([term, '-e', 'bash', '-c', script, '_'] + cmd_args, start_new_session=True)

def _execute_cmds(cmds: list, show_output: bool, notify: bool, name: str, shell: bool = False):
    def worker():
        for cmd in cmds:
            if show_output:
                _run_in_terminal(cmd, shell)
            else:
                if shell:
                    subprocess.Popen(cmd, shell=True, start_new_session=True)
                else:
                    subprocess.Popen(shlex.split(cmd), start_new_session=True)
        if notify:
            subprocess.Popen(["notify-send", "-i", "dialog-information", "ClickMesh", f"Action '{name}' completed."], start_new_session=True)
    threading.Thread(target=worker, daemon=True).start()

# ---------------------------------------------------------------------------
#  Action callbacks
# ---------------------------------------------------------------------------

def _on_action_0(menu_item, files):
    """Callback: Open Archive (GUI)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Open Archive (GUI)', shell=False)


def _on_action_1(menu_item, files):
    """Callback: Extract Here"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2here %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract Here', shell=False)


def _on_action_2(menu_item, files):
    """Callback: Extract to New Folder"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2folder %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract to New Folder', shell=False)


def _on_action_3(menu_item, files):
    """Callback: Extract... (Choose)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2here %file -gui'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract... (Choose)', shell=False)


def _on_action_4(menu_item, files):
    """Callback: Extract Selected File (GUI)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract Selected File (GUI)', shell=False)


def _on_action_5(menu_item, files):
    """Callback: Test Archive"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -test %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Test Archive', shell=False)


def _on_action_6(menu_item, files):
    """Callback: Add to ZIP"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2zip %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to ZIP', shell=False)


def _on_action_7(menu_item, files):
    """Callback: Add to 7Z"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add27z %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to 7Z', shell=False)


def _on_action_8(menu_item, files):
    """Callback: Add to TAR.GZ (Linux)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2tgz %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to TAR.GZ (Linux)', shell=False)


def _on_action_9(menu_item, files):
    """Callback: Add to ZST (Fast)"""
    if not shutil.which('peazip'):
        _show_error(f"Required binary '{ 'peazip' }' not found.")
        return
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2zst %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to ZST (Fast)', shell=False)


# ---------------------------------------------------------------------------
#  Menu Provider
# ---------------------------------------------------------------------------

class PeazipmenuExtension(GObject.GObject, Thunarx.MenuProvider):
    """Injects a '{{MENU_TITLE}}' submenu into the Thunar right-click menu."""

    def get_file_items(self, window, files):
        if not files:
            return []

        # --- ClickMesh Filtering (Per-Item Basis Setup) ---
        allow_dirs = True
        paths = [_path_from_item(f) for f in files]
        has_dir = any(os.path.isdir(p) for p in paths)
        has_file = any(not os.path.isdir(p) for p in paths)

        if has_dir and not allow_dirs:
            return []
        # --------------------------------------------------

        top_item = Thunarx.MenuItem(
            name="PeaZipMenu::TopMenu",
            label=_localize({'en': 'PeaZip', 'ar': 'بيزيب'}),
            tip=_localize({'en': 'PeaZip', 'ar': 'بيزيب'}),
            icon="peazip",
        )
        submenu = Thunarx.Menu()
        top_item.set_submenu(submenu)

        items_added = 0
        # --- Menu Tree Setup ---
        menus = {'': submenu}
        item_0_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso', '.cab', '.arj')
        item_0_allow_all = False
        show_item_0 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_0 = True
            elif has_file:
                if item_0_allow_all:
                    show_item_0 = True
                else:
                    show_item_0 = any(any(p.lower().endswith(ext) for ext in item_0_exts) for p in paths if not os.path.isdir(p))

        if show_item_0:
            item_0 = Thunarx.MenuItem(
                name="PeaZipMenu::Action0",
                label=_localize({'en': 'Open Archive (GUI)', 'ar': 'فتح الأرشيف (واجهة)'}),
                tip=_localize({'en': 'Open Archive (GUI)', 'ar': 'فتح الأرشيف (واجهة)'}),
                icon="peazip",
            )
            item_0.connect("activate", _on_action_0, files)
            menus[''].append_item(item_0)
            items_added += 1
        item_1_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso')
        item_1_allow_all = False
        show_item_1 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_1 = True
            elif has_file:
                if item_1_allow_all:
                    show_item_1 = True
                else:
                    show_item_1 = any(any(p.lower().endswith(ext) for ext in item_1_exts) for p in paths if not os.path.isdir(p))

        if show_item_1:
            if 'Extract' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_1 = Thunarx.MenuItem(
                name="PeaZipMenu::Action1",
                label=_localize({'en': 'Extract Here', 'ar': 'استخراج هنا'}),
                tip=_localize({'en': 'Extract Here', 'ar': 'استخراج هنا'}),
                icon="archive-extract",
            )
            item_1.connect("activate", _on_action_1, files)
            menus['Extract'].append_item(item_1)
            items_added += 1
        item_2_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst', '.tgz', '.tbz2', '.txz', '.tzst', '.001', '.iso')
        item_2_allow_all = False
        show_item_2 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_2 = True
            elif has_file:
                if item_2_allow_all:
                    show_item_2 = True
                else:
                    show_item_2 = any(any(p.lower().endswith(ext) for ext in item_2_exts) for p in paths if not os.path.isdir(p))

        if show_item_2:
            if 'Extract' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_2 = Thunarx.MenuItem(
                name="PeaZipMenu::Action2",
                label=_localize({'en': 'Extract to New Folder', 'ar': 'استخراج لمجلد جديد'}),
                tip=_localize({'en': 'Extract to New Folder', 'ar': 'استخراج لمجلد جديد'}),
                icon="folder-new",
            )
            item_2.connect("activate", _on_action_2, files)
            menus['Extract'].append_item(item_2)
            items_added += 1
        item_3_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst')
        item_3_allow_all = False
        show_item_3 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_3 = True
            elif has_file:
                if item_3_allow_all:
                    show_item_3 = True
                else:
                    show_item_3 = any(any(p.lower().endswith(ext) for ext in item_3_exts) for p in paths if not os.path.isdir(p))

        if show_item_3:
            if 'Extract' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_3 = Thunarx.MenuItem(
                name="PeaZipMenu::Action3",
                label=_localize({'en': 'Extract... (Choose)', 'ar': 'استخراج... (اختيار المكان)'}),
                tip=_localize({'en': 'Extract... (Choose)', 'ar': 'استخراج... (اختيار المكان)'}),
                icon="folder-remote",
            )
            item_3.connect("activate", _on_action_3, files)
            menus['Extract'].append_item(item_3)
            items_added += 1
        item_4_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst')
        item_4_allow_all = False
        show_item_4 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_4 = True
            elif has_file:
                if item_4_allow_all:
                    show_item_4 = True
                else:
                    show_item_4 = any(any(p.lower().endswith(ext) for ext in item_4_exts) for p in paths if not os.path.isdir(p))

        if show_item_4:
            if 'Extract' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            if 'Extract/Advanced Extract' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Extract/Advanced Extract', label=_localize({'en': 'Advanced Extract', 'ar': 'استخراج متقدم'}), tip=_localize({'en': 'Advanced Extract', 'ar': 'استخراج متقدم'}), icon='applications-system')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus['Extract'].append_item(group_item)
                menus['Extract/Advanced Extract'] = group_menu
            item_4 = Thunarx.MenuItem(
                name="PeaZipMenu::Action4",
                label=_localize({'en': 'Extract Selected File (GUI)', 'ar': 'استخراج ملف محدد (واجهة)'}),
                tip=_localize({'en': 'Extract Selected File (GUI)', 'ar': 'استخراج ملف محدد (واجهة)'}),
                icon="document-open",
            )
            item_4.connect("activate", _on_action_4, files)
            menus['Extract/Advanced Extract'].append_item(item_4)
            items_added += 1
        item_5_exts = ('.zip', '.7z', '.rar', '.tar', '.gz', '.bz2', '.xz', '.zst')
        item_5_allow_all = False
        show_item_5 = False

        if 0 <= len(files) <= 10:
            if has_dir and allow_dirs:
                show_item_5 = True
            elif has_file:
                if item_5_allow_all:
                    show_item_5 = True
                else:
                    show_item_5 = any(any(p.lower().endswith(ext) for ext in item_5_exts) for p in paths if not os.path.isdir(p))

        if show_item_5:
            if 'Extract' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            if 'Extract/Advanced Extract' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Extract/Advanced Extract', label=_localize({'en': 'Advanced Extract', 'ar': 'استخراج متقدم'}), tip=_localize({'en': 'Advanced Extract', 'ar': 'استخراج متقدم'}), icon='applications-system')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus['Extract'].append_item(group_item)
                menus['Extract/Advanced Extract'] = group_menu
            item_5 = Thunarx.MenuItem(
                name="PeaZipMenu::Action5",
                label=_localize({'en': 'Test Archive', 'ar': 'فحص الأرشيف'}),
                tip=_localize({'en': 'Test Archive', 'ar': 'فحص الأرشيف'}),
                icon="dialog-ok",
            )
            item_5.connect("activate", _on_action_5, files)
            menus['Extract/Advanced Extract'].append_item(item_5)
            items_added += 1
        item_6_exts = ('.txt', '.pdf', '.mp4', '.mkv', '.mp3', '.jpg', '.png', '.doc', '.docx', '.zip', '.7z')
        item_6_allow_all = False
        show_item_6 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_6 = True
            elif has_file:
                if item_6_allow_all:
                    show_item_6 = True
                else:
                    show_item_6 = any(any(p.lower().endswith(ext) for ext in item_6_exts) for p in paths if not os.path.isdir(p))

        if show_item_6:
            if 'Add to Archive' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            item_6 = Thunarx.MenuItem(
                name="PeaZipMenu::Action6",
                label=_localize({'en': 'Add to ZIP', 'ar': 'إضافة إلى ZIP'}),
                tip=_localize({'en': 'Add to ZIP', 'ar': 'إضافة إلى ZIP'}),
                icon="package-x-generic",
            )
            item_6.connect("activate", _on_action_6, files)
            menus['Add to Archive'].append_item(item_6)
            items_added += 1
        item_7_exts = ('.txt', '.pdf', '.mp4', '.mkv', '.mp3', '.jpg', '.png', '.doc', '.docx', '.zip', '.7z')
        item_7_allow_all = False
        show_item_7 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_7 = True
            elif has_file:
                if item_7_allow_all:
                    show_item_7 = True
                else:
                    show_item_7 = any(any(p.lower().endswith(ext) for ext in item_7_exts) for p in paths if not os.path.isdir(p))

        if show_item_7:
            if 'Add to Archive' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            item_7 = Thunarx.MenuItem(
                name="PeaZipMenu::Action7",
                label=_localize({'en': 'Add to 7Z', 'ar': 'إضافة إلى 7Z'}),
                tip=_localize({'en': 'Add to 7Z', 'ar': 'إضافة إلى 7Z'}),
                icon="package-x-generic",
            )
            item_7.connect("activate", _on_action_7, files)
            menus['Add to Archive'].append_item(item_7)
            items_added += 1
        item_8_exts = ('.txt', '.pdf', '.mp4', '.mkv', '.mp3', '.jpg', '.png')
        item_8_allow_all = False
        show_item_8 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_8 = True
            elif has_file:
                if item_8_allow_all:
                    show_item_8 = True
                else:
                    show_item_8 = any(any(p.lower().endswith(ext) for ext in item_8_exts) for p in paths if not os.path.isdir(p))

        if show_item_8:
            if 'Add to Archive' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Professional' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Add to Archive/Professional', label=_localize({'en': 'Professional', 'ar': 'احترافي'}), tip=_localize({'en': 'Professional', 'ar': 'احترافي'}), icon='package-x-generic')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Professional'] = group_menu
            item_8 = Thunarx.MenuItem(
                name="PeaZipMenu::Action8",
                label=_localize({'en': 'Add to TAR.GZ (Linux)', 'ar': 'إضافة إلى TAR.GZ'}),
                tip=_localize({'en': 'Add to TAR.GZ (Linux)', 'ar': 'إضافة إلى TAR.GZ'}),
                icon="package-x-generic",
            )
            item_8.connect("activate", _on_action_8, files)
            menus['Add to Archive/Professional'].append_item(item_8)
            items_added += 1
        item_9_exts = ('.txt', '.pdf', '.mp4', '.mkv', '.mp3', '.jpg', '.png')
        item_9_allow_all = False
        show_item_9 = False

        if 0 <= len(files) <= 100:
            if has_dir and allow_dirs:
                show_item_9 = True
            elif has_file:
                if item_9_allow_all:
                    show_item_9 = True
                else:
                    show_item_9 = any(any(p.lower().endswith(ext) for ext in item_9_exts) for p in paths if not os.path.isdir(p))

        if show_item_9:
            if 'Add to Archive' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Professional' not in menus:
                group_item = Thunarx.MenuItem(name='PeaZipMenu::Add to Archive/Professional', label=_localize({'en': 'Professional', 'ar': 'احترافي'}), tip=_localize({'en': 'Professional', 'ar': 'احترافي'}), icon='package-x-generic')
                group_menu = Thunarx.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Professional'] = group_menu
            item_9 = Thunarx.MenuItem(
                name="PeaZipMenu::Action9",
                label=_localize({'en': 'Add to ZST (Fast)', 'ar': 'إضافة إلى ZST (سريع)'}),
                tip=_localize({'en': 'Add to ZST (Fast)', 'ar': 'إضافة إلى ZST (سريع)'}),
                icon="package-x-generic",
            )
            item_9.connect("activate", _on_action_9, files)
            menus['Add to Archive/Professional'].append_item(item_9)
            items_added += 1
        if items_added == 0:
            return []

        return [top_item]
