#!/usr/bin/env python3
"""
PeaZipMenu — ClickMesh-generated context menu extension for Nautilus (GNOME Files).
Auto-generated by ClickMesh. Edit the source JSON and re-generate instead of
modifying this file directly.
"""

import os
import shlex
import subprocess
import shutil
import threading
from urllib.parse import unquote

import gi
from gi.repository import Nautilus, GObject

# ---------------------------------------------------------------------------
#  Helpers
# ---------------------------------------------------------------------------

def _localize(val):
    if isinstance(val, str): return val
    lang = os.environ.get('LANG', 'en').split('.')[0].split('_')[0]
    return val.get(lang, val.get('en', next(iter(val.values())) if val else ''))

def _path_from_item(file_item):
    """Extract a local filesystem path from a Nautilus FileInfo object."""
    uri = file_item.get_uri()
    if uri.startswith("file://"):
        return unquote(uri[7:])
    return unquote(uri)

def _confirm(message: str) -> bool:
    if shutil.which('zenity'):
        res = subprocess.run(['zenity', '--question', '--text', message], capture_output=True)
        return res.returncode == 0
    if shutil.which('kdialog'):
        res = subprocess.run(['kdialog', '--yesno', message], capture_output=True)
        return res.returncode == 0
    return True

def _show_error(message: str):
    if shutil.which('zenity'):
        subprocess.run(['zenity', '--error', '--text', message])
    elif shutil.which('kdialog'):
        subprocess.run(['kdialog', '--error', message])
    elif shutil.which('notify-send'):
        subprocess.run(['notify-send', '-i', 'dialog-error', 'ClickMesh Error', message])

def _run_in_terminal(cmd: str, shell: bool = False):
    terms = ['x-terminal-emulator', 'gnome-terminal', 'konsole', 'xfce4-terminal', 'xterm']
    term = next((t for t in terms if shutil.which(t)), None)
    
    if not term:
        if shell:
            subprocess.Popen(cmd, shell=True, start_new_session=True)
        else:
            subprocess.Popen(shlex.split(cmd), start_new_session=True)
        return

    if shell:
        script = f"{cmd}; echo; read -p 'Press Enter to close...'"
        if term in ['gnome-terminal', '/usr/bin/gnome-terminal']:
            subprocess.Popen([term, '--', 'bash', '-c', script], start_new_session=True)
        else:
            subprocess.Popen([term, '-e', 'bash', '-c', script], start_new_session=True)
    else:
        cmd_args = shlex.split(cmd)
        script = 'mcmd="$1"; shift; "$mcmd" "$@"; echo; read -p "Press Enter to close..."'
        if term in ['gnome-terminal', '/usr/bin/gnome-terminal']:
            subprocess.Popen([term, '--', 'bash', '-c', script, '_'] + cmd_args, start_new_session=True)
        else:
            subprocess.Popen([term, '-e', 'bash', '-c', script, '_'] + cmd_args, start_new_session=True)

def _execute_cmds(cmds: list, show_output: bool, notify: bool, name: str, shell: bool = False):
    def worker():
        for cmd in cmds:
            if show_output:
                _run_in_terminal(cmd, shell)
            else:
                if shell:
                    subprocess.Popen(cmd, shell=True, start_new_session=True)
                else:
                    subprocess.Popen(shlex.split(cmd), start_new_session=True)
        if notify:
            subprocess.Popen(["notify-send", "-i", "dialog-information", "ClickMesh", f"Action '{name}' completed."], start_new_session=True)
    threading.Thread(target=worker, daemon=True).start()

# ---------------------------------------------------------------------------
#  Action callbacks
# ---------------------------------------------------------------------------

def _on_action_0(menu_item, files):
    """Callback: Open Archive (GUI)"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Open Archive (GUI)', shell=False)


def _on_action_1(menu_item, files):
    """Callback: Extract Here"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2here %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract Here', shell=False)


def _on_action_2(menu_item, files):
    """Callback: Extract to New Folder"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2folder %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract to New Folder', shell=False)


def _on_action_3(menu_item, files):
    """Callback: Extract... (Choose)"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -ext2here %file -gui'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Extract... (Choose)', shell=False)


def _on_action_4(menu_item, files):
    """Callback: Add to ZIP"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2zip %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to ZIP', shell=False)


def _on_action_5(menu_item, files):
    """Callback: Add to 7Z"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add27z %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to 7Z', shell=False)


def _on_action_6(menu_item, files):
    """Callback: Add to TAR.GZ"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2tgz %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to TAR.GZ', shell=False)


def _on_action_7(menu_item, files):
    """Callback: Add to TAR.ZST"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2tzst %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Add to TAR.ZST', shell=False)


def _on_action_8(menu_item, files):
    """Callback: Create Encrypted Archive"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2crypt %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Create Encrypted Archive', shell=False)


def _on_action_9(menu_item, files):
    """Callback: Create SFX Archive"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2sfx %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Create SFX Archive', shell=False)


def _on_action_10(menu_item, files):
    """Callback: Split into Volumes"""
    cmds = []
    count = len(files)
    for file_item in files:
        path = _path_from_item(file_item)
        _dir = os.path.dirname(path)
        _filename = os.path.basename(path)
        _basename, _ext = os.path.splitext(_filename)
        if _ext.startswith('.'): _ext = _ext[1:]
        cmd = 'peazip -add2split %file'
        cmd = cmd.replace('%count', str(count))
        cmd = cmd.replace('%filename', shlex.quote(_filename))
        cmd = cmd.replace('%basename', shlex.quote(_basename))
        cmd = cmd.replace('%ext', shlex.quote(_ext))
        cmd = cmd.replace('%dir', shlex.quote(_dir))
        cmd = cmd.replace('%file', shlex.quote(path))
        cmds.append(cmd)
    _execute_cmds(cmds, show_output=False, notify=False, name='Split into Volumes', shell=False)


# ---------------------------------------------------------------------------
#  Menu Provider
# ---------------------------------------------------------------------------

class PeazipmenuExtension(GObject.GObject, Nautilus.MenuProvider):
    """Injects a '{{MENU_TITLE}}' submenu into the Nautilus right-click menu."""

    def get_file_items(self, *args):
        files = args[-1] if args else []
        if not files:
            return []

        # --- ClickMesh Filtering (Per-Item Basis Setup) ---
        allow_dirs = True
        paths = [_path_from_item(f) for f in files]
        has_dir = any(os.path.isdir(p) for p in paths)
        has_file = any(not os.path.isdir(p) for p in paths)

        if has_dir and not allow_dirs:
            return []
        # --------------------------------------------------

        # --- Top-level menu item (acts as a submenu header) -----------------
        top_item = Nautilus.MenuItem(
            name="PeaZipMenu::TopMenu",
            label=_localize({'en': 'PeaZip', 'ar': 'بيزيب'}),
            tip=_localize({'en': 'PeaZip', 'ar': 'بيزيب'}),
            icon="peazip",
        )
        submenu = Nautilus.Menu()
        top_item.set_submenu(submenu)

        # --- Submenu entries ------------------------------------------------
        items_added = 0
        # --- Menu Tree Setup ---
        menus = {'': submenu}
        item_0_exts = ('.@', '.a', '.l', '.l', '._', '.a', '.r', '.c', '.h', '.i', '.v', '.e', '.s')
        item_0_allow_all = False
        show_item_0 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_0 = True
            elif has_file:
                if item_0_allow_all:
                    show_item_0 = True
                else:
                    show_item_0 = any(any(p.lower().endswith(ext) for ext in item_0_exts) for p in paths if not os.path.isdir(p))

        if show_item_0:
            item_0 = Nautilus.MenuItem(
                name="PeaZipMenu::Action0",
                label=_localize({'en': 'Open Archive (GUI)', 'ar': 'فتح الأرشيف (واجهة)'}),
                tip=_localize({'en': 'Open Archive (GUI)', 'ar': 'فتح الأرشيف (واجهة)'}),
                icon="peazip",
            )
            item_0.connect("activate", _on_action_0, files)
            menus[''].append_item(item_0)
            items_added += 1
        item_1_exts = ('.@', '.c', '.o', '.m', '.m', '.o', '.n', '._', '.a', '.r', '.c', '.h', '.i', '.v', '.e', '.s')
        item_1_allow_all = False
        show_item_1 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_1 = True
            elif has_file:
                if item_1_allow_all:
                    show_item_1 = True
                else:
                    show_item_1 = any(any(p.lower().endswith(ext) for ext in item_1_exts) for p in paths if not os.path.isdir(p))

        if show_item_1:
            if 'Extract' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_1 = Nautilus.MenuItem(
                name="PeaZipMenu::Action1",
                label=_localize({'en': 'Extract Here', 'ar': 'استخراج هنا'}),
                tip=_localize({'en': 'Extract Here', 'ar': 'استخراج هنا'}),
                icon="",
            )
            item_1.connect("activate", _on_action_1, files)
            menus['Extract'].append_item(item_1)
            items_added += 1
        item_2_exts = ('.@', '.c', '.o', '.m', '.m', '.o', '.n', '._', '.a', '.r', '.c', '.h', '.i', '.v', '.e', '.s')
        item_2_allow_all = False
        show_item_2 = False

        if 0 <= len(files) <= 20:
            if has_dir and allow_dirs:
                show_item_2 = True
            elif has_file:
                if item_2_allow_all:
                    show_item_2 = True
                else:
                    show_item_2 = any(any(p.lower().endswith(ext) for ext in item_2_exts) for p in paths if not os.path.isdir(p))

        if show_item_2:
            if 'Extract' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_2 = Nautilus.MenuItem(
                name="PeaZipMenu::Action2",
                label=_localize({'en': 'Extract to New Folder', 'ar': 'استخراج لمجلد جديد'}),
                tip=_localize({'en': 'Extract to New Folder', 'ar': 'استخراج لمجلد جديد'}),
                icon="folder-new",
            )
            item_2.connect("activate", _on_action_2, files)
            menus['Extract'].append_item(item_2)
            items_added += 1
        item_3_exts = ('.@', '.b', '.a', '.s', '.i', '.c', '._', '.a', '.r', '.c', '.h', '.i', '.v', '.e', '.s')
        item_3_allow_all = False
        show_item_3 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_3 = True
            elif has_file:
                if item_3_allow_all:
                    show_item_3 = True
                else:
                    show_item_3 = any(any(p.lower().endswith(ext) for ext in item_3_exts) for p in paths if not os.path.isdir(p))

        if show_item_3:
            if 'Extract' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Extract', label=_localize({'en': 'Extract', 'ar': 'استخراج'}), tip=_localize({'en': 'Extract', 'ar': 'استخراج'}), icon='archive-extract')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Extract'] = group_menu
            item_3 = Nautilus.MenuItem(
                name="PeaZipMenu::Action3",
                label=_localize({'en': 'Extract... (Choose)', 'ar': 'استخراج... (اختيار المكان)'}),
                tip=_localize({'en': 'Extract... (Choose)', 'ar': 'استخراج... (اختيار المكان)'}),
                icon="folder-remote",
            )
            item_3.connect("activate", _on_action_3, files)
            menus['Extract'].append_item(item_3)
            items_added += 1
        item_4_exts = ()
        item_4_allow_all = True
        show_item_4 = False

        if 0 <= len(files) <= 999999:
            if has_dir and allow_dirs:
                show_item_4 = True
            elif has_file:
                if item_4_allow_all:
                    show_item_4 = True
                else:
                    show_item_4 = any(any(p.lower().endswith(ext) for ext in item_4_exts) for p in paths if not os.path.isdir(p))

        if show_item_4:
            if 'Add to Archive' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            item_4 = Nautilus.MenuItem(
                name="PeaZipMenu::Action4",
                label=_localize({'en': 'Add to ZIP', 'ar': 'إضافة إلى ZIP'}),
                tip=_localize({'en': 'Add to ZIP', 'ar': 'إضافة إلى ZIP'}),
                icon="",
            )
            item_4.connect("activate", _on_action_4, files)
            menus['Add to Archive'].append_item(item_4)
            items_added += 1
        item_5_exts = ()
        item_5_allow_all = True
        show_item_5 = False

        if 0 <= len(files) <= 999999:
            if has_dir and allow_dirs:
                show_item_5 = True
            elif has_file:
                if item_5_allow_all:
                    show_item_5 = True
                else:
                    show_item_5 = any(any(p.lower().endswith(ext) for ext in item_5_exts) for p in paths if not os.path.isdir(p))

        if show_item_5:
            if 'Add to Archive' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            item_5 = Nautilus.MenuItem(
                name="PeaZipMenu::Action5",
                label=_localize({'en': 'Add to 7Z', 'ar': 'إضافة إلى 7Z'}),
                tip=_localize({'en': 'Add to 7Z', 'ar': 'إضافة إلى 7Z'}),
                icon="",
            )
            item_5.connect("activate", _on_action_5, files)
            menus['Add to Archive'].append_item(item_5)
            items_added += 1
        item_6_exts = ()
        item_6_allow_all = True
        show_item_6 = False

        if 0 <= len(files) <= 999999:
            if has_dir and allow_dirs:
                show_item_6 = True
            elif has_file:
                if item_6_allow_all:
                    show_item_6 = True
                else:
                    show_item_6 = any(any(p.lower().endswith(ext) for ext in item_6_exts) for p in paths if not os.path.isdir(p))

        if show_item_6:
            if 'Add to Archive' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Linux & Pro' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive/Linux & Pro', label=_localize({'en': 'Linux & Pro', 'ar': 'لينكس واحترافي'}), tip=_localize({'en': 'Linux & Pro', 'ar': 'لينكس واحترافي'}))
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Linux & Pro'] = group_menu
            item_6 = Nautilus.MenuItem(
                name="PeaZipMenu::Action6",
                label=_localize({'en': 'Add to TAR.GZ', 'ar': 'إضافة إلى TAR.GZ'}),
                tip=_localize({'en': 'Add to TAR.GZ', 'ar': 'إضافة إلى TAR.GZ'}),
                icon="",
            )
            item_6.connect("activate", _on_action_6, files)
            menus['Add to Archive/Linux & Pro'].append_item(item_6)
            items_added += 1
        item_7_exts = ()
        item_7_allow_all = True
        show_item_7 = False

        if 0 <= len(files) <= 999999:
            if has_dir and allow_dirs:
                show_item_7 = True
            elif has_file:
                if item_7_allow_all:
                    show_item_7 = True
                else:
                    show_item_7 = any(any(p.lower().endswith(ext) for ext in item_7_exts) for p in paths if not os.path.isdir(p))

        if show_item_7:
            if 'Add to Archive' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Linux & Pro' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive/Linux & Pro', label=_localize({'en': 'Linux & Pro', 'ar': 'لينكس واحترافي'}), tip=_localize({'en': 'Linux & Pro', 'ar': 'لينكس واحترافي'}))
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Linux & Pro'] = group_menu
            item_7 = Nautilus.MenuItem(
                name="PeaZipMenu::Action7",
                label=_localize({'en': 'Add to TAR.ZST', 'ar': 'إضافة إلى TAR.ZST'}),
                tip=_localize({'en': 'Add to TAR.ZST', 'ar': 'إضافة إلى TAR.ZST'}),
                icon="",
            )
            item_7.connect("activate", _on_action_7, files)
            menus['Add to Archive/Linux & Pro'].append_item(item_7)
            items_added += 1
        item_8_exts = ()
        item_8_allow_all = True
        show_item_8 = False

        if 0 <= len(files) <= 999999:
            if has_dir and allow_dirs:
                show_item_8 = True
            elif has_file:
                if item_8_allow_all:
                    show_item_8 = True
                else:
                    show_item_8 = any(any(p.lower().endswith(ext) for ext in item_8_exts) for p in paths if not os.path.isdir(p))

        if show_item_8:
            if 'Add to Archive' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Advanced & Security' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive/Advanced & Security', label=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), tip=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), icon='preferences-system-security')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Advanced & Security'] = group_menu
            item_8 = Nautilus.MenuItem(
                name="PeaZipMenu::Action8",
                label=_localize({'en': 'Create Encrypted Archive', 'ar': 'إنشاء أرشيف مشفر'}),
                tip=_localize({'en': 'Create Encrypted Archive', 'ar': 'إنشاء أرشيف مشفر'}),
                icon="dialog-password",
            )
            item_8.connect("activate", _on_action_8, files)
            menus['Add to Archive/Advanced & Security'].append_item(item_8)
            items_added += 1
        item_9_exts = ()
        item_9_allow_all = True
        show_item_9 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_9 = True
            elif has_file:
                if item_9_allow_all:
                    show_item_9 = True
                else:
                    show_item_9 = any(any(p.lower().endswith(ext) for ext in item_9_exts) for p in paths if not os.path.isdir(p))

        if show_item_9:
            if 'Add to Archive' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Advanced & Security' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive/Advanced & Security', label=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), tip=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), icon='preferences-system-security')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Advanced & Security'] = group_menu
            item_9 = Nautilus.MenuItem(
                name="PeaZipMenu::Action9",
                label=_localize({'en': 'Create SFX Archive', 'ar': 'أرشيف ذاتي الاستخراج (SFX)'}),
                tip=_localize({'en': 'Create SFX Archive', 'ar': 'أرشيف ذاتي الاستخراج (SFX)'}),
                icon="application-x-executable",
            )
            item_9.connect("activate", _on_action_9, files)
            menus['Add to Archive/Advanced & Security'].append_item(item_9)
            items_added += 1
        item_10_exts = ()
        item_10_allow_all = True
        show_item_10 = False

        if 0 <= len(files) <= 1:
            if has_dir and allow_dirs:
                show_item_10 = True
            elif has_file:
                if item_10_allow_all:
                    show_item_10 = True
                else:
                    show_item_10 = any(any(p.lower().endswith(ext) for ext in item_10_exts) for p in paths if not os.path.isdir(p))

        if show_item_10:
            if 'Add to Archive' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive', label=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), tip=_localize({'en': 'Add to Archive', 'ar': 'إضافة لأرشيف'}), icon='archive-insert')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus[''].append_item(group_item)
                menus['Add to Archive'] = group_menu
            if 'Add to Archive/Advanced & Security' not in menus:
                group_item = Nautilus.MenuItem(name='PeaZipMenu::Add to Archive/Advanced & Security', label=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), tip=_localize({'en': 'Advanced & Security', 'ar': 'حماية ومتقدم'}), icon='preferences-system-security')
                group_menu = Nautilus.Menu()
                group_item.set_submenu(group_menu)
                menus['Add to Archive'].append_item(group_item)
                menus['Add to Archive/Advanced & Security'] = group_menu
            item_10 = Nautilus.MenuItem(
                name="PeaZipMenu::Action10",
                label=_localize({'en': 'Split into Volumes', 'ar': 'تقسيم الملف إلى أجزاء'}),
                tip=_localize({'en': 'Split into Volumes', 'ar': 'تقسيم الملف إلى أجزاء'}),
                icon="view-split-left-right",
            )
            item_10.connect("activate", _on_action_10, files)
            menus['Add to Archive/Advanced & Security'].append_item(item_10)
            items_added += 1
        if items_added == 0:
            return []

        return [top_item]
